apiVersion: v1
kind: Pod
metadata:
  name: busy-box
  labels:
    app: busy-box
spec:
  containers:
  - name: busy-box
    image: busybox:latest
    command:
      ["/bin/sh", "-c", "printenv APP_ENV APP_DEBUG APP_PORT; sleep 3600"]
    envFrom:
    - configMapRef:
        name: app-config


