apiVersion: v1
kind: Pod
metadata:
  name: live-pod
spec:
  containers:
  - name: live-pod
    image: busybox:latest
    command: ["/bin/sh","-c"]
    args:
      - |
        while true; do
          echo "message=$(cat /config/message)";
          sleep 5;
        done
    volumeMounts:
      - name: msg-vol
        mountPath: /config
  volumes:
    - name: msg-vol
      configMap:
        name: live-config
