apiVersion: v1
kind: Pod
metadata:
  name: dynamic-pod
spec:
  containers:
    - name: dynamic-pod
      image: busybox:1.26
      command: ["/bin/sh", "-c"]
      args:
        - echo "Hello from Dynamic PVC" > /data/index.txt && sleep 3600
      volumeMounts:
        - name: dynamic-storage
          mountPath: /data
  volumes:
    - name: dynamic-storage
      persistentVolumeClaim:
        claimName: dynamic-provisioning
